Changed type and updated CMakelists
rodperex/behaviorfleets pull request #5
Opened 2023-11-13 17:33 UTC by Juancams

Changes made:
- PortInfo -> TypeInfo // portInfo -> EntryInfo
- Update CMakeLists.txt

With these changes, the package is compiled correctly and the libraries are exported correctly. With this, we can correct this rodperex/bf_patrol#1

2023-11-13 18:47 UTC, fmrico commented
The `ament_target_dependencies` also have to be for libraries ;)

2023-11-15 10:51 UTC, rodperex requested changes
Thanks for your review, just some minor changes.

2023-11-15 10:51 UTC, rodperex commented on behaviorfleets/src/behaviorfleets/BlackboardHandler.cpp
> +  const BT::TypeInfo * port = blackboard_->entryInfo(port_name);
please do not upgrade yet to the new definitions

2023-11-15 10:51 UTC, rodperex commented on behaviorfleets/src/behaviorfleets/BlackboardManager.cpp
> +  const BT::TypeInfo * port = bb->entryInfo(port_name);
same

2023-11-15 10:51 UTC, rodperex commented on behaviorfleets/src/behaviorfleets/BlackboardManager.cpp
>    // const BT::TypeInfo * port = blackboard_->entryInfo(port_name);
same

2023-11-15 11:08 UTC, merged